### PR TITLE
[v1.99] Rename truncation to deletion deprecations

### PR DESCRIPTION
**Pull request by botandrose**
v1.99 deprecation companion PR for:
* https://github.com/DatabaseCleaner/database_cleaner-mongo/pull/7
* https://github.com/DatabaseCleaner/database_cleaner-mongoid/pull/12
* https://github.com/DatabaseCleaner/database_cleaner-redis/pull/10

### CODE REVIEW

**Comment by botandrose** [comment]
@etagwerker Okay! I think that both this PR and https://github.com/DatabaseCleaner/database_cleaner/pull/653 (and their v2.0 companion PRs) represent readiness for releasing v1.99.0.beta and v2.0.0.beta for all gems.

What do you think?

**Comment by botandrose** [comment]
@etagwerker I was hoping to release beta versions of v1.99 and v2.0 this weekend. Any objection to me merging these PRs and doing so?

**Comment by etagwerker** [comment]
@botandrose Re: Releasing 1.99. 

Maybe I missed it, but are there deprecation messages being printed when someone is loading their cleaner using "the old way"?

**Comment by botandrose** [comment]
@etagwerker What do you mean by the old way? You mean via autodetect instead of explicit gems?

**Comment by etagwerker** [comment]
@botandrose Yes, that's it. We can continue this discussion over here: https://gitter.im/DatabaseCleaner/community

**Pull request merged**
