### PR TITLE
Fix database object for mongoid version beyond 5

### PR DESCRIPTION
**Pull request by prabhakar97**
database_cleaner errors out with following message with Mongoid 5. This pull request fixes that without breaking anything else.

> /home/prabhakar/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/database_cleaner-f052d64d3be9/lib/database_cleaner/mongo2/truncation_mixin.rb:29:in collections: undefined method collections for #&lt;Mongo::Client:0x47021052998580 cluster=127.0.0.1:27017&gt; (NoMethodError)
>   from /home/prabhakar/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/database_cleaner-f052d64d3be9/lib/database_cleaner/mongo2/truncation_mixin.rb:9:in clean
>   from /home/prabhakar/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/database_cleaner-f052d64d3be9/lib/database_cleaner/base.rb:92:in clean
>   from /home/prabhakar/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/database_cleaner-f052d64d3be9/lib/database_cleaner/configuration.rb:79:in block in clean
>   from /home/prabhakar/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/database_cleaner-f052d64d3be9/lib/database_cleaner/configuration.rb:79:in each
>   from /home/prabhakar/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/database_cleaner-f052d64d3be9/lib/database_cleaner/configuration.rb:79:in clean

### CODE REVIEW

**Comment by jgonzalezd** [comment]
Sad to see this PR never made it to the repo. I'm on the latest version of DB cleaner `1.7.0` and I'm hitting this issue.

**Comment by prabhakar97** [comment]
You can fork your own and cherry pick this commit :-)

**Comment by jgonzalezd** [comment]
I actually did it, but ended up with almost 1K active connections to the DB when running `parallel:spec` I had to revert it.

**Comment by etagwerker** [comment]
@prabhakar97 @jgonzalezd Sorry for the delay. 

@prabhakar97 could you solve the conflict and update this PR? It seems pretty straightforward and I could merge this after you do that.

**Comment by prabhakar97** [comment]
@etagwerker Thanks, I have fixed the conflict. But weird that the CI is failing. I see all recently opened PRs too failing in travis.

**Comment by botandrose** [comment]
Thank you for the PR! However, the Mongoid adapter has been extracted into its own repo at https://github.com/DatabaseCleaner/database_cleaner-mongoid. If you close this PR and reopen it over there, I'd be happy to take a look!

**Pull request closed without merging**
