### PR TITLE
Remove stray require 'mongoid/tree'

### LINKED ISSUE #299: The 'truncation' strategy does not exist [...] Available strategies: truncation
Hi everybody. As the title suggests there seems to be a bit of a missmatch in the way that mongoid strategies are determined in the current master. 

This is the full error message ([which is raised from here](https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/base.rb#L137)): 

```
The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation
```

And as you can see, "truncation" appears on the list of available strategies. I tried assigning the strategy as a string and a symbol, but both resulted in this problem.

Any suggestions, or is this a bug?

### PR DESCRIPTION
**Pull request by TimMoore**
Closes #299.

### CODE REVIEW

**Comment by lucke84** [comment]
Please merge :)))

**Comment by gurix** [comment]
:+1:

**Comment by mkempe** [comment]
:+1:

**Comment by rentalname** [comment]
:+1:

**Comment by etagwerker** [comment]
@TimMoore Great, thanks!

**Comment by TimMoore** [comment]
Thank, you!

**Comment by tagliala** [comment]
Could you please release a hotfix?

**Comment by lucke84** [comment]
@tagliala +1

**Comment by rye** [comment]
+1 @tagliala, @lucke84

**Comment by tricknotes** [comment]
+1 for release.
Current latest version 1.4.0 doesn't  work with mongoid :cry:

**Comment by gurix** [comment]
@tricknotes you have to reference to github instead of using rubygems. @etagwerker an official fix 1.4.1 would be nice of corse.

**Pull request merged**
