### PR TITLE
Fix travis build error and expand test matrix

### PR DESCRIPTION
**Pull request by lostapathy**
Attempting to fix the error leading to broken travis build and add ruby 2.3 to the test matrix.

This also updates the json dep so that more recent versions of ruby can build this gem - resolves #448

As is noted on #488, it's really not best practice to keep Gemfile.lock in the repo for a gem.  Looks like maintainers have changed - are we open to that now?  If so, I would work on PR for that and on expanding the test matrix to test this against various rails versions.  Thanks

### CODE REVIEW

**Comment by lostapathy** [comment]
Well - this fixes the immediate error Travis was having, but there are still some (pre-existing, I believe) failing tests.  I'll try to loop around and look at those, but hopefully this PR is at least a little help.

**Comment by etagwerker** [comment]
@lostapathy Thanks for your contribution! 

> As is noted on #488, it's really not best practice to keep Gemfile.lock in the repo for a gem. Looks like maintainers have changed - are we open to that now?

Yes, we're open to that. I started working on that but had to focus on something else. It'd be great if you can work on a PR for that.

**Comment by lostapathy** [comment]
I'll take a stab at it.  @etagwerker how far back to you want to maintain support in the matrix?  I try not to include unsupported ruby or rails versions unless there's a really compelling reason, but looks like the current build goes back to ruby-1.9.3 and rails-3.0

**Comment by etagwerker** [comment]
@lostapathy I think it's a good idea to move towards supported ruby/rails versions.

**Comment by etagwerker** [comment]
@lostapathy I just took at stab at this and I now remember why it is so hard. `database_cleaner` has a lot of development dependencies. I believe it's way too many for any maintainer.

So, this task seems quite hard for `database_cleaner` < 2.0. Last year I started working on `database_cleaner` 2.0 but then got side tracked and couldn't finish it. If you're open to new contribution ideas, your time might be best spent on `database_cleaner` 2.0. 

The idea behind 2.0 is to have smaller gems with more manageable dependencies (e.g. database_cleaner-active_record)

In these smaller gems, we will be able to add `appraisals` to make it easier to test different dependencies (e.g. activerecord 4.2, 5.0, and 5.1)

**Comment by lostapathy** [comment]
I removed the Gemfile lock and bundler takes ~45 minutes to resolve all the development dependencies.  

Yes - I agree 100%, the right way forward is to split this into several smaller gems, like a "core" + strategies for each database.

**Pull request closed without merging**
