### PR TITLE
Bump supported Ruby versions

### PR DESCRIPTION
**Pull request by botandrose**
Ruby 2.1 has been EOL for over a year.

https://www.ruby-lang.org/en/downloads/branches/

### CODE REVIEW

**Comment by botandrose** [comment]
Interesting. To support Ruby 2.4 and 2.5, it looks like we'd have to drop support for the old `mysql` gem, which no longer compiles on those versions. This gem hasn't been maintained since 2013: https://rubygems.org/gems/mysql , so dropping support for it is easy to justify, but we'd probably want to major bump the database_cleaner version to v2.0.0. Thoughts?

**Comment by saiqulhaq** [comment]
mysql2 still support ruby 2.0.0
https://github.com/brianmario/mysql2/blob/master/.travis.yml

**Comment by botandrose** [comment]
@saiqulhaq Ah, that's good enough for me, then. I'll restore 2.0.0 and 2.1 to the matrix.

**Comment by botandrose** [comment]
@etagwerker Doing a little digging, I found your comments about splitting up this gem into multiples for database_cleaner v2.0 to restore sanity. I agree something like that is necessary for any progress to be made on this front. Closing.

**Pull request closed without merging**
