### PR TITLE
Make the NullStrategy API-complete

### LINKED ISSUE #443: NullStrategy isn't API-complete
In my app, I had my RSpec setup to use `:transaction` as the default strategy:

```ruby

def default_cleaning_strategy
  :transaction
end

RSpec.configure do |config|
  # <snip>
   config.before(:suite) do
    DatabaseCleaner.strategy = default_cleaning_strategy
    DatabaseCleaner.clean_with(:truncation)
  end
end
```

I also had some tests that make big (multi-thousand-row INSERT big) db calls. Wanting to compromise neither my test-suite time nor my nice clean single-expectation specs, I thought "I'll just use the `NullStrategy` for this group":

```ruby

describe "long-running db tests" do
  before(:all) do 
    DatabaseCleaner.strategy = nil
    perform_db_operation #one-time cost
  end

  after(:all) do
    DatabaseCleaner.strategy = default_cleaning_strategy
    DatabaseCleaner.clean_with :truncation
  end
  
  it "etc." do
    # <snip>
  end
end
```

but no dice:

```
  8) <test name>
     Failure/Error:
       DatabaseCleaner.cleaning do
         example.run
       end
     
     NoMethodError:
       undefined method `cleaning' for DatabaseCleaner::NullStrategy:Class
     # /Users/andy/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.2/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/andy/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.2/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/andy/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.2/lib/database_cleaner/configuration.rb:87:in `call'
     # /Users/andy/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.2/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/spec_helper.rb:119:in `block (2 levels) in <top (required)>'
```

Shouldn't the `NullStrategy` implement the entire API for strategies?

### PR DESCRIPTION
**Pull request by anicholson**
Fixes #443 .

### CODE REVIEW

**Comment by etagwerker** [comment]
@anicholson Great, thanks! Could you add a basic spec for `null_strategy.rb`?

**Comment by anicholson** [comment]
@etagweker sure 😀

**Comment by anicholson** [comment]
@etagwerker done :)

**Comment by etagwerker** [comment]
@anicholson Great, thanks! 👍

**Pull request merged**
