### PR TITLE
Add doc for creating new adapters

### PR DESCRIPTION
**Pull request by TheSmartnik**
Following https://github.com/DatabaseCleaner/database_cleaner/issues/628

### CODE REVIEW

**Comment by TheSmartnik** [comment]
@botandrose I've added WIP doc as you asked me in https://github.com/DatabaseCleaner/database_cleaner/issues/628#issuecomment-610091081

I haven't managed to follow it fully since `2.0.0` is not yet published

**Comment by botandrose** [comment]
@TheSmartnik This is really great! Thank you! I'll be doing some more refactoring and test improvement groundwork in a few PRs over the next few days, and I expect I'll merge this after that. Having a documented baseline for where the ORM adapter interface is _right now_ is going to be extremely useful for evaluating future PRs that attempt to improve it! I'm expecting we can simplify it quite a bit before v2.0.

**Comment by TheSmartnik** [comment]
@botandrose awesome, glad you liked it :)

**Comment by botandrose** [comment]
Thanks again, @TheSmartnik!

Since we're not quite ready for people to actually follow these instructions, I'm going to split this content out into its own file, with a big warning up top saying as much. Once v2.0.0 is out the door, it will be restored to the README.

**Pull request merged**
