### PR TITLE
gives an explicit return of ActiveRecord::Base for establish connection

### PR DESCRIPTION
**Pull request by awilkening**
instead of what ActiveRecord::Base.establish_connection returns

### CODE REVIEW

**Comment by awilkening** [comment]
https://github.com/DatabaseCleaner/database_cleaner/issues/398

**Comment by etagwerker** [comment]
@awilkening Thank you for your contribution! Could you add a failing scenario for this?

**Comment by awilkening** [comment]
@etagwerker I'm sorry, I'm not sure what you mean. Are you looking for a test that imitates the issue?

**Comment by awilkening** [comment]
@etagwerker I've added a change to an existing spec that was not testing the return value of #establish_connection in the active record base class.

**Comment by etagwerker** [comment]
@awilkening Thanks! Merged here: https://github.com/DatabaseCleaner/database_cleaner/commit/83c485cdfa91982449d20664cd90416c3b1e45b4

**Pull request closed without merging**
