### PR TITLE
#332 - mysql2+jruby support, speedup

### PR DESCRIPTION
**Pull request by ahorek**
#332

### CODE REVIEW

**Comment by etagwerker** [comment]
@ahorek Thank you for your contributon! But could you make sure that the build passes with `jruby`?

**Comment by ahorek** [comment]
@etagwerker Yes, it works well on mri and jruby (both tested with postgres and mysql2 adapters). Different configurations should work aswell.

**Comment by ahorek** [comment]
I can ensure rspec compatibility with jruby, but it would require many changes.

**Comment by creddy** [comment]
Any chance on getting this merged?

**Comment by etagwerker** [comment]
@ahorek Ok, thank you! :+1:

**Pull request merged**
